logo: # add logo name
title: 趣三碎
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: 1364145333@qq.com # your email
phone: 15545008962 # your pnone number
website: http://www.shengshimeiyan0808.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link 
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

weibo_url: https://weibo.com/u/3607850130
github_url: https://github.com/yidiudiu
email_url: mailto://1364145333@qq.com
wechat_url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU0MzQzNjA0Mw==&scene=124#wechat_redirect
zhihu_url: http://www.zhihu.com/people/hou-bao-ling-62


# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]